// פרסומות שותפי הקהילה — מקור: אתר "קהילה בשכונה".
// השדה color הוא ערך CSS gradient מוכן לשימוש (background).

export const ads = [
	{
		id: 11,
		title: "החנות החברתית",
		description: "מוצרים נבחרים לבריאות טבעית, חקלאות ביתית, טכנולוגיה ועוד",
		cta: "כנסו לחנות לחיים טובים יותר",
		href: "https://heirut-shop.vercel.app/",
		image: "/assets/freedom-store.png",
		color: "linear-gradient(90deg, #059669, #0d9488)",
	},
	{
		id: 1,
		title: "בתי הפיוס",
		description: "מתנדבים לתת לך עזרה מלאה בדין / פיוס בכל סיכסוך",
		cta: "יש לך סיכסוך? לחץ לפתרון",
		href: "https://chachmim.vercel.app/",
		image: "/assets/bati-hapius.png",
		color: "linear-gradient(90deg, #ea580c, #dc2626)",
	},
	{
		id: 9,
		title: 'הגמ"ח הארצי',
		description: "כל הגמחים תחת קורת גג אחת",
		cta: 'לאתר הגמ"ח הארצי',
		hover: "מצא כל גמח בקלות!",
		href: "https://national-gemach.vercel.app/",
		image: "/assets/gemach-harzi.png",
		color: "linear-gradient(90deg, #db2777, #c026d3, #7e22ce)",
	},
	{
		id: 2,
		title: "ועדי שכונות",
		description: "מהפכת משילות העם על המוסדות",
		cta: "הכר והשתתף במהפכת משילות העם על מוסדותיו",
		href: "https://www.melecshop.com/page/peace-on-earth_VRHH",
		image: "/assets/news/vaadei-shchunot.png",
		color: "linear-gradient(90deg, #2563eb, #0891b2)",
	},
	{
		id: 5,
		title: "מבקר רשויות המדינה",
		description: "מבקרים את הרשויות, ממצים את זכות התושב",
		cta: "מבקרים את הרשויות, ממצים את זכות התושב",
		href: "https://right-to-live.vercel.app/",
		image: "/assets/mevaker-rashuyot.png",
		color: "linear-gradient(90deg, #1d4ed8, #4338ca)",
	},
	{
		id: 10,
		title: "דירוג ציבורי",
		description: "העם מדרג את הרשויות ועובדי הציבור",
		cta: "העם מדרג את הרשויות ועובדי הציבור",
		href: "https://public-rating-il.vercel.app/",
		image: "/assets/public-rating.jpeg",
		color: "linear-gradient(90deg, #4f46e5, #2563eb)",
	},
	{
		id: 8,
		title: "משאלי העם",
		description: "הבע דעתך על הסוגיות האקטואליות",
		cta: "הבע דעתך על הסוגיות האקטואליות",
		hover: "הבע דעתך על הסוגיות האקטואליות",
		href: "https://referendum-azure.vercel.app/",
		image: "/assets/referendum.png",
		color: "linear-gradient(90deg, #9333ea, #4338ca)",
	},
	{
		id: 3,
		title: "קבוצת רכישה",
		description: "הוזל את ההוצאות שלך",
		cta: "הצטרף לקבוצת הרכישה שלנו והוזל מיד את ההוצאות!",
		href: "https://purchasing-groups.vercel.app/",
		image: "/assets/whatsapp_cta.png",
		color: "linear-gradient(90deg, #166534, #064e3b)",
	},
	{
		id: 4,
		title: "מועדון המשקיעים החברתי",
		description: "התחבר עם קבוצת המשקיעים שלנו",
		cta: "התחבר עם קבוצת המשקיעים שלנו",
		href: "https://www.melecshop.com/page/free",
		image: "/assets/partners/investments.png",
		color: "linear-gradient(90deg, #d97706, #ea580c)",
	},
	{
		id: 6,
		title: "בעלי מקצוע כשירים",
		description: "חתמו על תנאי הקהילה ונותנים לנו הנחות והטבות יחודיות",
		cta: "מחפש בעל מקצוע איכותי באזורך?",
		href: "https://index-chi-sage.vercel.app/",
		image: "/assets/professionals.png",
		color: "linear-gradient(90deg, #eab308, #f97316)",
	},
];
